### ISSUE TITLE
How to sync in the OpenEye license?

### ISSUE THREAD

**Issue by ghost** [CBDD/openduck#22]
Hi I am trying to use the openduck protocol from AMBER. I have amber22 installed and openeye toolkits in my home folder as well. I installed openduck following the steps.
I then went to the example folder and ran this:
openduck amber-prepare -y test1.yaml -l ../../data/cdk2_lig.mol -r ../../data/2r3k.pdb

It says it cannot locate the openeye toolkits, how do I point it to the openeye toolkits installation? Also how do I point it to my amber22 installation folder location?
Thanks
<img width="1394" alt="image" src="https://github.com/CBDD/openduck/assets/106696539/c17392c7-de41-44e2-8ac2-113dbcd6e28a">

**Comment by AlvaroSmorras** [comment]
Hello @debarati31,
The OpenEye toolkit is a warning that is automatically pushed by the openff-toolkit library. OpenEye is not needed nor used for the openduck preparation.
The error you see in the examples on the test is a problem in the receptor (it has a dioxy-cystein, a non-standard residue). It is my mistake, as the tests are still not well setup. In order not to cause confusion I have moved them away from the main branch. If you require a tutorial or test system to learn the method I have a (still work in progress) tutorial here : https://github.com/AlvaroSmorras/openduck-tutorial , where the simulations are pre-computed. You are free to check it, of course.

Regarding 'pointing' the OpenEye and Amber installations to openduck, you don't need to do that. We use antechamber (sqm) to calculate the partial charges and the simulations are independent from the system preparation with openduck. Once you have the systems prepared, you can activate amber and launch the simulations (you can also do the preparation and the simulations in different computers, they are completely independent). Just ensure you have python3 with numpy available for the getWqbValues.py script.

I hope this answers your questions,
Álvaro
