### ISSUE TITLE
Cleanup intermediary files better

### ISSUE THREAD

**Issue by simonbray** [CBDD/openduck#8]
@AlvaroSmorras what do you think of deleting all intermediary files by default? We could still allow keeping them with a flag like `--keep-all-files`.

Currently 1 run generates ca. 150 files and if you want to screen thousands of molecules, this creates a really huge number of files. At the moment I'm cleaning up myself with `find -type f ! -regex ".*\(sdf\|dat\|nc\)$" -delete`, but this could be done directly within OpenDuCK as well.

**Comment by AlvaroSmorras** [comment]
Hi! As we talked, I agree to add this to the openduck script.
However, do you refer to the files generated during the run, the preparation, or both? I guess for openMM we could cleanup everything after the run, but in amber, the simulation is run externally through the queue files. In this regard, do you think its worth adding the flag to add a similar command to yours in the queue file?

**Comment by simonbray** [comment]
Hi, sorry for the slow reply - I was on vacation.

Yes, I meant cleaning up both files generated during preparation and the run itself. I agree, for amber it would make sense to add that command I wrote (or something similar) directly into the queue template file :+1:

**Comment by AlvaroSmorras** [comment]
Perfect! I have tried to limit the cleaning up files to the ones we create with the script (it is more wordy, as i enumerate the files to delete), but this way we avoid deleting files that the user had there independently from the openduck execution.
